### ISSUE TITLE
Possible incompatibility with chat mod

### ISSUE THREAD

**Issue by xela-the-proto** [DrexHD/MagicParticles#3]
**Minecraft version 1.21**
**Loader fabric, version 0.15.11**

When installed on a server  the player gets kicked out with the error **"io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:system_chat"**

## Steps to reproduce

- have magic particles installed
- apply any particle effect

## Full stack trace
https://gist.github.com/xela-the-proto/0ac707c7a78450eacd86266b4fd64266

**Comment by Xelaa-Dev** [comment]
nvm it aint the mod i tested after posting the issue and it still crashes im a dumb dumb
